name: RedwoodJS CI

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

env:
  DATABASE_URL: mysql://user:password@localhost:3306/universal
  TEST_DATABASE_URL: mysql://user:password@localhost:3306/universal

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: universal
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: rootpassword
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn rw lint

      - name: Build
        run: yarn rw build

      - name: Test `api` side
        run: yarn rw test api --no-watch

      - name: Test `web` side
        run: yarn rw test web --no-watch
